[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  environment = { VITE_API_URL = "https://weebraphael.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200